#!/usr/bin/env python3
"""harness/v3/state_assertion.py - capture_state_assertion schema + validator.

Defines the schema for capture_state_assertion.json and a syntactic
validator. The assertion is generated by the harness at capture time
(window title, button labels, timer value, state fingerprint) and
validated BEFORE accepting the capture as candidate for closure.

NO runtime authority. Does NOT close keys. Does NOT invoke capture_v8
(this module only defines the schema; the actual capture is orchestrated
by capture_orchestrator.py in a later fase). Does NOT invoke V1/V2.

Fase 2: syntactic validation only. Semantic validation (does the
assertion match the declared surface_key state?) is deferred.

Usage:
    python harness/v3/state_assertion.py --assertion <json_file>

Exit codes:
    0  VALID
    1  INVALID (reasons printed to stderr)
    2  ERROR
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REQUIRED_FIELDS = {
    "surface_key": str,
    "window_title": str,
    "button_labels": list,
    "state_fingerprint": str,
    "captured_at": str,
    "capture_v8_sha256": str,
}
OPTIONAL_FIELDS = {"timer_value"}


def validate(assertion: dict[str, Any]) -> tuple[bool, list[str]]:
    """Return (valid, reasons)."""
    reasons: list[str] = []
    if not isinstance(assertion, dict):
        return (False, ["assertion_not_object"])
    for field, expected_type in REQUIRED_FIELDS.items():
        if field not in assertion:
            reasons.append(f"missing_field:{field}")
            continue
        value = assertion[field]
        # bool is subclass of int; ensure str fields are str, list fields are list
        if expected_type is str and not isinstance(value, str):
            reasons.append(f"field_type_mismatch:{field}:expected_str")
        elif expected_type is list and not isinstance(value, list):
            reasons.append(f"field_type_mismatch:{field}:expected_list")
        elif expected_type is str and isinstance(value, str) and not value:
            reasons.append(f"empty_field:{field}")
    # surface_key must match pattern suite:...@light|dark or hub:...@light|dark
    sk = assertion.get("surface_key", "")
    if sk and "@" not in sk:
        reasons.append(f"surface_key_invalid_format:{sk}")
    elif sk and not (sk.endswith("@light") or sk.endswith("@dark")):
        reasons.append(f"surface_key_missing_theme:{sk}")
    # captured_at should be ISO8601-ish (presence check only)
    ca = assertion.get("captured_at", "")
    if ca and "T" not in ca:
        reasons.append("captured_at_not_iso8601")
    # capture_v8_sha256 should be 64 hex chars
    sha = assertion.get("capture_v8_sha256", "")
    if sha and (len(sha) != 64 or not all(c in "0123456789abcdef" for c in sha.lower())):
        reasons.append("capture_v8_sha256_not_sha256_hex")
    return (len(reasons) == 0, reasons)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assertion", required=True, type=Path)
    args = parser.parse_args()
    if not args.assertion.exists():
        print(f"ERROR: assertion file not found: {args.assertion}", file=sys.stderr)
        return 2
    try:
        data = json.loads(args.assertion.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"ERROR: invalid JSON: {e}", file=sys.stderr)
        return 2
    ok, reasons = validate(data)
    if ok:
        print("VALID: state_assertion")
        return 0
    print("INVALID: state_assertion", file=sys.stderr)
    for r in reasons:
        print(f"  - {r}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
