"""Compatibility facade for NeuroMood PyQt6 shared components.

Implementations live under ``shared.components`` leaf modules. New internal
imports should use ``shared.components``.
"""

from __future__ import annotations

from shared.components import (
    NMAIDisclaimer,
    NMAvatar,
    NMBadge,
    NMButton,
    NMButtonOutline,
    NMCalmBadge,
    NMCard,
    NMChartPanel,
    NMChip,
    NMCustomCheck,
    NMCycleRing,
    NMDayNote,
    NMDialogScaffold,
    NMDivider,
    NMElidedLabel,
    NMEmptyState,
    NMFadeWidget,
    NMFeaturedCard,
    NMFocusArc,
    NMFormPanel,
    NMFormRow,
    NMHeatBar,
    NMHubSidebar,
    NMIcon,
    NMInput,
    NMListRow,
    NMMetricCard,
    NMModule,
    NMModuleRing,
    NMPageHeader,
    NMPanel,
    NMPatientRowPremium,
    NMPhaseChip,
    NMPlayButton,
    NMProgressBar,
    NMProgressLine,
    NMRingPulse,
    NMSearchInput,
    NMSectionHeader,
    NMSegmentedChoice,
    NMSettingsSection,
    NMSkeleton,
    NMStepper,
    NMSyncOrb,
    NMTabs,
    NMTextArea,
    NMToast,
    NMToggle,
    NMTypingDots,
    NMWaveChart,
    NMWindowChrome,
    ThemeManager,
    V3MoodSlider,
    h_spacer,
    nm_confirm,
    responsive_columns,
)
from shared.components.inputs import NMSelect
from shared.components.layout import responsive_breakpoint

__all__ = [
    "NMAIDisclaimer",
    "NMAvatar",
    "NMBadge",
    "NMButton",
    "NMButtonOutline",
    "NMCalmBadge",
    "NMCard",
    "NMChartPanel",
    "NMChip",
    "NMCustomCheck",
    "NMCycleRing",
    "NMDayNote",
    "NMDialogScaffold",
    "NMDivider",
    "NMElidedLabel",
    "NMEmptyState",
    "NMFadeWidget",
    "NMFeaturedCard",
    "NMFocusArc",
    "NMFormPanel",
    "NMFormRow",
    "NMHeatBar",
    "NMHubSidebar",
    "NMIcon",
    "NMInput",
    "NMListRow",
    "NMMetricCard",
    "NMModule",
    "NMModuleRing",
    "NMPageHeader",
    "NMPanel",
    "NMPatientRowPremium",
    "NMPhaseChip",
    "NMPlayButton",
    "NMProgressBar",
    "NMProgressLine",
    "NMRingPulse",
    "NMSearchInput",
    "NMSectionHeader",
    "NMSegmentedChoice",
    "NMSettingsSection",
    "NMSkeleton",
    "NMStepper",
    "NMSyncOrb",
    "NMTabs",
    "NMTextArea",
    "NMToast",
    "NMToggle",
    "NMTypingDots",
    "NMWaveChart",
    "NMWindowChrome",
    "ThemeManager",
    "V3MoodSlider",
    "h_spacer",
    "nm_confirm",
    "responsive_columns",
]
