"""Compatibility facade for NeuroMood PyQt6 shared components.

Implementations live under ``shared.components`` leaf modules. New internal
imports should use ``shared.components``.
"""

from __future__ import annotations

from shared.components import (
    NMAvatar,
    NMBadge,
    NMButton,
    NMButtonOutline,
    NMCard,
    NMChartPanel,
    NMChip,
    NMCustomCheck,
    NMDialogScaffold,
    NMElidedLabel,
    NMEmptyState,
    NMFadeWidget,
    NMFocusArc,
    NMHeatBar,
    NMIcon,
    NMInput,
    NMModule,
    NMModuleRing,
    NMPageHeader,
    NMPatientRowPremium,
    NMPlayButton,
    NMProgressBar,
    NMRingPulse,
    NMSearchInput,
    NMSectionHeader,
    NMSegmentedChoice,
    NMStepper,
    NMTabs,
    NMTextArea,
    NMToast,
    NMWaveChart,
    NMWindowChrome,
    ThemeManager,
    V3MoodSlider,
    nm_confirm,
)

__all__ = [
    "NMAvatar",
    "NMBadge",
    "NMButton",
    "NMButtonOutline",
    "NMCard",
    "NMChartPanel",
    "NMChip",
    "NMCustomCheck",
    "NMDialogScaffold",
    "NMElidedLabel",
    "NMEmptyState",
    "NMFadeWidget",
    "NMFocusArc",
    "NMHeatBar",
    "NMIcon",
    "NMInput",
    "NMModule",
    "NMModuleRing",
    "NMPageHeader",
    "NMPatientRowPremium",
    "NMPlayButton",
    "NMProgressBar",
    "NMRingPulse",
    "NMSearchInput",
    "NMSectionHeader",
    "NMSegmentedChoice",
    "NMStepper",
    "NMTabs",
    "NMTextArea",
    "NMToast",
    "NMWaveChart",
    "NMWindowChrome",
    "ThemeManager",
    "V3MoodSlider",
    "nm_confirm",
]
